# Generated by Django 5.1.1 on 2024-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, help_text='Укажите время выполнения привычки', null=True, verbose_name='Время'),
        ),
    ]
